---
micronaut:
  application:
    name: jconf20Demo
  server:
    cors:
      enabled: true
kafka:
  bootstrap:
    servers: nv-mabdulkader:9092

datasources:
  default:
    sql-dialect: 'POSTGRES'
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/jconf
    username: jconf

flyway:
  datasources:
    default:
      enabled: true